name: Lint

on: [ push, pull_request ]

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Poetry
        run: poetry --version

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry -n install --with lint

      - name: Check minimum required version
        run: poetry run vermin -v --backport typing --eval-annotations --no-parse-comments src/

      - name: Analyze for minimum required version
        run: poetry run pyright --pythonversion 3.12 src/

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Add Poetry to PATH
        run: echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Verify Poetry
        run: poetry --version

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry -n install --with lint

      - name: Lint project
        run: poetry run pylint src/
